### ISSUE TITLE
arm 64 release include many amd64 bin, is it correct?

### ISSUE THREAD

**Issue by zhugcx** [snight1983/chia-rosechain#10]
arm 64 release include many amd64 bin, is it correct?

**Comment by snight1983** [comment]
The arm program packaged in ubuntu may not be correct, and it lacks equipment for compilation verification for the time being. Wait for everyone to test and ask questions, I will make changes. At present, it is difficult for one person to maintain it. I hope that some enthusiasts can participate in it one day.
