### ISSUE TITLE
Netspace at 345 EIB Linux mint (bug?)

### ISSUE THREAD

**Issue by shinary2** [snight1983/chia-rosechain#14]
OS: Ubuntu mint 
Issue: netspace at 345EIB
reproduce: install on linux mint
Still found proofs and get rewarded, but only issue that the netspace is bugged :)

**Comment by snight1983** [comment]
It is a display bug that does not affect the operation of the program:)

**Comment by snight1983** [comment]
https://github.com/snight1983/chia-rosechain/commit/57d8b8025373ec64a1685d8414ae3d9b7d12fb30
