### ISSUE TITLE
为什么只给了我25个XCR ？

### ISSUE THREAD

**Issue by xgdd1987** [snight1983/chia-rosechain#21]
目标地址：xcr1qgcl204j7lmt7zvpyyus8hrau57z99c2v3hnjrxs0n3q8vwznaysyaq7m3
日期：07/22/2021 上午3:12:08
确认于区块高度 316283

爆块不应该是给200个吗？

谢谢。

**Comment by snight1983** [comment]
你用的新图把，老外175去了黑洞了。新图是和chia的区块做了绑定了，确切的说是 新图的池奖励，绑定到chia的区块上了。Rose没法子跨链去Chia上面去取信息，暂时那175没有很好的取出解决方案。

**Comment by xgdd1987** [comment]
好的，谢谢提醒。
我的新图也没有加入任何池啊，自己solo的，为啥才给25？

**Comment by xgdd1987** [comment]
兄弟，能解决下吗？每次都只给25个，少太多了。再这样下去不能挖了。

**Comment by PapiDot** [comment]
> 兄弟，能解决下吗？每次都只给25个，少太多了。再这样下去不能挖了。

或参考TAD网络的解决办法。https://github.com/Tad-Network/tad-blockchain
“Farmers get FULL reward with existing portable NFT and OG plots”

**Comment by snight1983** [comment]
https://github.com/Tad-Network/tad-blockchain 这种方式不是解决问题，是功能阉割，没有意义。
