### ISSUE TITLE
网站https://chiarose.com/关闭已经快一周了。

### ISSUE THREAD

**Issue by zhangyongchang88** [snight1983/chia-rosechain#32]
嗨，
网站https://chiarose.com/关闭已经快一周了。
我们应该停止耕种还是什么？
这个项目死了吗？

请尽快通知。

谢谢

**Comment by snight1983** [comment]
换域名，硬分叉后有空再弄官网，有事来github看公告便是。新域名 www.rosechain.net

**Comment by snight1983** [comment]
Change the domain name and get the official website when you have time after the hard fork. If you have something to do, come to github to read the announcement. New domain name www.rosechain.net
