### ISSUE TITLE
XCR Faucet Website Not Working

### ISSUE THREAD

**Issue by wrjmhb21** [snight1983/chia-rosechain#42]
How to get the 0.000001 to join pool farming? When I click on  Pool >>> Add XCR From the Faucet, it redirects to chia faucet website: https://faucet.chia.net/, can you check and fix the bug? 

Also can you send some XCR to my address: 
xcr1vy4kpwys20flw4uktd7ww950lln9t62mrup9c23lagkljad5erpsquchkr

**Comment by snight1983** [comment]
Has been sent for you.

**Comment by wrjmhb21** [comment]
Received! Thank you!
