### ISSUE TITLE
Please Fix URL Errors

### ISSUE THREAD

**Issue by wrjmhb21** [snight1983/chia-rosechain#43]
Version: RoseChain Pool 1.3.2

Farming  - RoseChain Explorer URL
Current： *Want to explore Chia’s blocks further? Check out Chia Explorer built by an open source developer.
Correct： *Want to explore RoseChain blocks further? Check out RoseChain Explorer built by an open source developer.
Current URL: https://www.chiaexplorer.com/
Correct URL: Please update URL

URLs in File Menu - Help

Release Note：
Current URL: https://github.com/Chia-Network/chia-blockchain/releases
Correct URL: https://github.com/snight1983/chia-rosechain/releases

Contribute：
Current URL: https://github.com/Chia-Network/chia-blockchain/blob/main/CONTRIBUTING.md
Correct URL: https://github.com/snight1983/chia-rosechain/blob/main/CONTRIBUTING.md

Report an Issue：
Current URL: https://github.com/Chia-Network/chia-blockchain/issues
Correct URL: https://github.com/snight1983/chia-rosechain/issues

Report an Issue：
Current URL: https://github.com/Chia-Network/chia-blockchain/issues
Correct URL: https://github.com/snight1983/chia-rosechain/issues

Chat on KeyBase
Current URL: https://keybase.io/team/chia_network.public
Correct URL: https://keybase.io/team/rosechainnet

Follow on Twitter:
Current URL: https://twitter.com/chia_project
Correct URL: Please Update URL

**Comment by snight1983** [comment]
OK , the next version will be replaced uniformly.

**Comment by wrjmhb21** [comment]
Also, you should also change the Logo, as the current log is very similar to Chia.
