### ISSUE TITLE
[BUG] Unable to sync

### ISSUE THREAD

**Issue by a1432568133** [snight1983/chia-rosechain#46]
Need the latest node to complete synchronization
![微信截图_20210911094403](https://user-images.githubusercontent.com/90487672/132932255-7f1d4e5f-c547-4623-b6dd-d5965d8e2d74.png)

**Comment by snight1983** [comment]
peer_table_node.7z  
https://github.com/snight1983/chia-rosechain/releases/download/1.3.0/peer_table_node.7z

**Comment by a1432568133** [comment]
How should I use
