### ISSUE TITLE
[BUG] Full nodes problems

### ISSUE THREAD

**Issue by olgyan93btc** [snight1983/chia-rosechain#52]
Hello,
What do you think about this?
This is normal or I have a problem with the system.
see attached file
![ROSE](https://user-images.githubusercontent.com/83642938/135073695-6b781ea8-1f58-4347-9f13-011f9abf9e9b.jpg)

**Comment by snight1983** [comment]
The node that maintains the height of 475624 is for players who have not yet upgraded They cannot synchronize the blocks. Unless they upgrade to the latest version.

**Comment by snight1983** [comment]
If you can synchronize the blocks normally, there is no problem with your version.
