### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ramonMontanhes** [snight1983/chia-rosechain#7]
How can I install it on linux?

**Comment by Brubolm** [comment]
same question

**Comment by snight1983** [comment]
I'm sorry I didn't make the linux installation package. I will make it recently. If you have time, or you can directly use the source code to compile, the way of compiling is exactly the same as that of chia.

**Comment by ramonMontanhes** [comment]
I have compiled it but the GUI does not works. I think its does not comes with the GUI folder on the project like I can find in others projects, could you check this please?

I can still run this by CLI?

**Comment by snight1983** [comment]
The gui source code has not been submitted yet, you can try to execute it with the command line. I do not have enough time and conditions to improve the linux and mac versions. 
The original chia version of the gui, I haven't tried it that way, it should show some unpredictable displays.

**Comment by ramonMontanhes** [comment]
@snight1983 could you explain how to run this by CLI? I'm afraid of running it with and cause double farming with my chia pool.

I could install it and use . ./activate, after this if I run the command chia it will be running with the rosechain network? Could you assure this?

Also, where should I put the db file that you provide to download?

**Comment by ramonMontanhes** [comment]
Forget this, I downloaded the new code and I was running the gui that you have added @snight1983 

@Brubolm check the new code it will work as sparecoin instructions.

**Comment by snight1983** [comment]
O(∩_∩)O
